import "./globals.css";

import type { Metadata } from "next";
import { Raleway } from "next/font/google";

import { Providers } from "@/app/providers";

const font = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fatih Emin - Medyanes360 Task",
  description: "Generated by Fek",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
